name: flake8 code validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/check-out@v2
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: run flake8
        run: flake8 ./
